_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
cpus_per_task: 10 # Increased to avoid bottleneck on fast H200s
gpus_per_node: 1
tasks_per_node: 1
mem_gb: 32
nodes: 1
name: ${task_name}
partition: "short"
signal_delay_s: 120
max_num_timeout: 0
additional_parameters:
  constraint: "H200"
timeout_min: 420 # 7 hrs
array_parallelism: 256
