# configs/hydra/launcher/lightning.yaml
_target_: src.utils.lightning_launcher.LightningLauncher

# Pull from environment variables
studio_name: ${oc.env:LIGHTNING_STUDIO_NAME}
teamspace: ${oc.env:LIGHTNING_TEAMSPACE}
user: ${oc.env:LIGHTNING_USER}

# Resource settings
machine: "A10G"
setup_command: "uv pip install -e . && uv pip install lightning-sdk"
